[package]
name = "adaptuner"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
midi-msg = "0.6.1"
midir = "0.9.1"
ratatui = {version = "0.26.1", features = ["unstable-widget-ref"]}
ndarray = {version = "0.15.6", features = ["serde"]}
num-integer = "0.1.46"
num-traits = "0.2.18"
fractionfree = "0.1.3"
colorous = "1.0.13"
serde_derive = "1.0.198"
ctrlc = "3.4.4"
deser-hjson = "2.2.4"
serde = "1.0.204"
eframe = "0.29.1"
egui = { version = "0.29.1", features = ["color-hex"] }
epaint = "0.29.1"
emath = "0.29.1"
indextree = "4.7.3"

[dev-dependencies]
approx = "0.5.1"
pretty_assertions = "1.4.0"
