[package]
name = "adaptuner"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.27.0"
midi-msg = "0.6.1"
midir = "0.9.1"
ratatui = {version = "0.26.1", features = ["unstable-widget-ref"]}
ndarray = "0.15.6"
num-integer = "0.1.46"
num-traits = "0.2.18"
fractionfree = "0.1.3"
colorous = "1.0.13"

[dev-dependencies]
approx = "0.5.1"
