name: "build"

on:
  push:
    branches: [ "main" ]
    tags: 
      - "**"
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build -L .#adaptuner-bin
      - uses: actions/upload-artifact@v4
        with:
          name: adaptuner-bin-aarch64-darwin
          path: result/*
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build -L .#adaptuner-bin
      - uses: actions/upload-artifact@v4
        with:
          name: adaptuner-bin-x86_64-linux
          path: result/*
      - run: nix build -L .#adaptuner-deb
      - uses: actions/upload-artifact@v4
        with:
          name: adaptuner-deb-x86_64-linux
          path: result/*
      - run: nix build -L .#adaptuner-mingw
      - uses: actions/upload-artifact@v4
        with:
          name: adaptuner-x86_64-w64-mingw32
          path: result/*
  release:
    if: startsWith(github.event.ref, 'refs/tags')
    needs: [build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - run: for i in adaptuner-*; do zip -r $i $i; done
      - uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: adaptuner-*.zip
